### ISSUE TITLE
[https://www.paypal.com/paypalme/recom3com/52](https://www.paypal.com/paypalme/recom3com/52)

### ISSUE THREAD

**Issue by TerryPanos** [recom3/api-hud-goggle#12]
[https://www.paypal.com/paypalme/recom3com/52](https://www.paypal.com/paypalme/recom3com/52)

Ok as you prefer. Full unblock but only 3 months access to site...

_Originally posted by @recom3 in https://github.com/recom3/api-hud-goggle/issues/6#issuecomment-2052455397_

**Comment by TerryPanos** [comment]
Hi I’m just about to purchase the unlock for my recom jet sunglasses via the PayPal link you sent me but I’m. It sure how you are going to send me the login details. Do you need my email address or can you tell from my payment thanks Terry

**Comment by TerryPanos** [comment]
https://www.paypal.com/paypalme/recom3com/52
this is the link you sent me

**Comment by recom3** [comment]
We can take from paypal, but just in case put your mail here (don't put the @ symbol, just an space)

**Comment by TerryPanos** [comment]
Terry.panos gmail.com what like this ? Can you send me the link please.
Thank you

Regards

Terry Panos

**Comment by TerryPanos** [comment]
Also does it have to be windows 10 or higher for it to work

Regards

Terry Panos
