### ISSUE TITLE
Error when going to the trip map

### ISSUE THREAD

**Issue by Romkabouter** [recom3/api-hud-goggle#4]
Hi,

I have synchronized my goggle after the latest snowboard trip, but when I go the map I see the following error in the debug console:

![Schermafbeelding 2023-02-13 om 13 26 56](https://user-images.githubusercontent.com/4774478/218457491-299ebdd6-bb23-4cc5-8ddd-e0438fe31d35.png)

**Comment by recom3** [comment]
Ok... strange. Checking it!

**Comment by recom3** [comment]
I think is a problem with Session Token validity.
Try this while we check: Logout and login again. After that go to trips again

**Comment by Romkabouter** [comment]
Ah, that seems to be the problem indeed!
I have logged out and then logged back in:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/4774478/218519967-d2d4bcda-4eba-4768-8d87-b179b859b0e7.png">

**Comment by recom3** [comment]
Nice trip!

**Comment by recom3** [comment]
In any case, we are releasing a new version to the web, with a new grid for selecting trip display.
This version will check token expiration too.

**Comment by recom3** [comment]
Deployed grid for trips and added more control to token expiration.
We are going to close the issue.

**Comment by Romkabouter** [comment]
works! Thanks
