### ISSUE TITLE
Trips are not updated in map when clicking in the grid

### ISSUE THREAD

**Issue by recom3** [recom3/api-hud-goggle#7]
When you enter your private area and go to trips, there is a grid showing your trips in descending order.

Trip si updated in the map when clicking in trip Id column, but not in the other columns.

This is an issue in the website.

**Comment by Romkabouter** [comment]
I think this is fixed right? Clicking anywhere on a row is changing the trip as expected for me.

**Comment by recom3** [comment]
We have fixed today at the end.
So it is fixed yes.
